# ----------------------------------------------------------------------------------
#                      r u s t f m t   -   C O N F I G
# ==================================================================================
# 
# Toml version: 0.1.0
# Package: Ditto
#
# A predefined .rustfmt.toml file for the project Ditto.
# To see which configurations are modified, please search for "MODIFIED".
#
# ----------------------------------------------------------------------------------

# Rust language edition to be used by the parser.
# edition = "2021"

# Version of the formatting rules to use.
# version = "Two"

# Unstable
unstable_features = true
wrap_comments = true
comment_width = 80
format_code_in_doc_comments = true
tab_spaces = 4
format_strings = true
max_width = 80
